# Generated by Django 4.0.3 on 2022-03-07 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('ultimo_nome', models.CharField(max_length=100)),
                ('contato', models.EmailField(max_length=254)),
                ('pretensao_salarial', models.CharField(choices=[('Até 1.000', 'Até 1.000'), ('De 1.000 a 2.000', 'De 1.000 a 2.000'), ('De 2.000 a 3.000', 'De 2.000 a 3.000'), ('Acima de 3.000', 'Acima de 3.000')], max_length=20)),
                ('experiencia', models.TextField(max_length=500)),
                ('ultima_escolaridade', models.CharField(choices=[('Ensino fundamental', 'FUNDAMENTAL'), ('Ensino médio', 'MEDIO'), ('Tecnólogo', 'TECNOLOGO'), ('Ensino Superior', 'SUPERIOR'), ('Pós / MBA / Mestrado', 'POS'), ('Doutorado', 'DOUTORADO')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Escolhidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('primeiro_contato', models.BooleanField(default=False, verbose_name='email padrao')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilulo', models.CharField(max_length=100)),
                ('visualizados', models.IntegerField(default=0)),
                ('total_candidatos', models.IntegerField(default=0)),
                ('lancamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('escolaridade', models.CharField(choices=[('Ensino fundamental', 'FUNDAMENTAL'), ('Ensino médio', 'MEDIO'), ('Tecnólogo', 'TECNOLOGO'), ('Ensino Superior', 'SUPERIOR'), ('Pós / MBA / Mestrado', 'POS'), ('Doutorado', 'DOUTORADO')], max_length=20)),
                ('faixa_salarial', models.CharField(choices=[('Até 1.000', 'Até 1.000'), ('De 1.000 a 2.000', 'De 1.000 a 2.000'), ('De 2.000 a 3.000', 'De 2.000 a 3.000'), ('Acima de 3.000', 'Acima de 3.000')], max_length=20)),
                ('requisitos', models.TextField(max_length=1000)),
            ],
        ),
    ]
