# Generated by Django 4.0.3 on 2022-03-07 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sujeito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_vagas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='jobs_vistos',
            field=models.ManyToManyField(to='sujeito.candidato'),
        ),
        migrations.AddField(
            model_name='aplicados',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_candidatos', to='job.job'),
        ),
    ]
