# Generated by Django 4.0.3 on 2022-03-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('sujeito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_vagas', to='sujeito.empresa'),
        ),
    ]
